#!/opt/dkvm/bin/sh

. /opt/dkvm/scripts/dkvm-ctr-defaults && PATH="$DKVM_PATH"

# dkvm-init execs this script when it exits.
# It:
# - performs any post-VM tests.
# - retrieves any saved exit code.
# - 

if [ -f /.dkvm/exitcode ]; then
  read CODE </.dkvm/exitcode

  # Convert negative codes to positive and ensure in acceptable range (0-255)
  CODE=$(( $CODE & 255 ))
elif [ -n "$1" ]; then
  CODE=$(( ($1+1)/2 ))
fi

# Workaround for https://github.com/cirosantilli/linux-kernel-module-cheat/issues/110
tput smam

exit ${CODE:-0}