#!/opt/dkvm/bin/bash

# TODO Rationalise these into defaults

. /opt/dkvm/scripts/dkvm-ctr-defaults

if [ -f /.dkvm/once ]; then
  poweroff
  exit 0
else
  touch /.dkvm/once
fi

# Load original entrypoint and environment
mapfile -t ARGS <<< $(cat /.dkvm/entrypoint)
. /.dkvm/export

IFS=':' read -r uid gid <<< "$DKVM_UIDGID"
exec $DKVM/bin/s6-applyuidgid -u $uid -g $gid -G "" "${ARGS[@]}"
# exec "${ARGS[@]}"