#!/opt/dkvm/bin/bash

# dkvm-init forks and execs this script when it receives a SIGTERM

poweroff() {
  # Try ACPI poweroff
  /opt/dkvm/scripts/dkvm-ctr-qemu-poweroff
  
  # Try running busybox poweroff
  /opt/dkvm/scripts/dkvm-ctr-exec 0:0 / /opt/dkvm/bin/poweroff
}

poweroff

exit 0
