#!/opt/dkvm/bin/bash

# TODO Rationalise these into defaults
DKVM=/opt/dkvm
PATH=$DKVM/sbin:$DKVM/bin:$DKVM/usr/bin
unset DKVM

if [ -f /.dkvm/once ]; then
  poweroff
  exit 0
else
  touch /.dkvm/once
fi

# Load original entrypoint and environment
mapfile -t ARGS <<< $(cat /.dkvm/entrypoint)
. /.dkvm/export

exec "${ARGS[@]}"
