#!/.runcvm/guest/bin/bash

# Load defaults and aliases
. /.runcvm/guest/scripts/runcvm-ctr-defaults

if [ "$RUNCVM_SYS_ADMIN" = "1" ]; then
  OPTS+=(-o modcaps=+sys_admin)
fi

VIRTIOFSD_CACHE=${RUNCVM_VIRTIOFSD_CACHE:-auto}
OPTS+=(-o "cache=$VIRTIOFSD_CACHE")

# Send logs to /run in container (not in VM)
exec "$(which virtiofsd)" "${OPTS[@]}" -o announce_submounts -o xattr --socket-path=$QEMU_VIRTIOFSD_SOCKET -o source=$RUNCVM_VM_MOUNTPOINT -o sandbox=chroot >/run/.virtiofsd.log 2>&1
