#!/.runcvm/guest/bin/bash

# Load original environment
. /.runcvm/config

# Load defaults and aliases
. $RUNCVM_GUEST/scripts/runcvm-ctr-defaults

# Clear all environment (set by busybox init)
exec -c $RUNCVM_GUEST/scripts/runcvm-vm-start