#!/.runcvm/guest/bin/bash

# runcvm-init forks and execs this script when it receives a SIGTERM

# Load original environment
. /.runcvm/config

poweroff() {
  # Try ACPI poweroff
  $RUNCVM_GUEST/scripts/runcvm-ctr-qemu-poweroff
  
  # Try running busybox poweroff
  $RUNCVM_GUEST/scripts/runcvm-ctr-exec 0:0 / 0 0 $RUNCVM_GUEST/bin/poweroff &>/dev/null

  # Try killing the VM's PID 1
  $RUNCVM_GUEST/scripts/runcvm-ctr-exec 0:0 / 0 0 $RUNCVM_GUEST/bin/busybox kill 1 &>/dev/null
}

poweroff

exit 0
