#!/opt/runcvm/bin/bash

. /opt/runcvm/scripts/runcvm-ctr-defaults && PATH="$RUNCVM_PATH"

if [ -f /.runcvm/once ]; then
  poweroff
  exit 0
else
  touch /.runcvm/once
fi

# Change to saved PWD
cd $(cat /.runcvm/pwd)

# Load original environment
. /.runcvm/config

# Load original entrypoint
mapfile -t ARGS </.runcvm/entrypoint

# Clean RUNCVM env vars
clean_env

IFS=':' read -r uid gid additionalGids <<< "$RUNCVM_UIDGID"
exec $RUNCVM/bin/s6-applyuidgid -u $uid -g $gid -G "$additionalGids" "${ARGS[@]}"