#!/opt/runcvm/guest/bin/bash

. /opt/runcvm/scripts/runcvm-vm-defaults && PATH="$RUNCVM_PATH"

if [ -f /.runcvm/once ]; then
  poweroff
  exit 0
else
  touch /.runcvm/once
fi

# Change to saved PWD
cd $(cat /.runcvm/pwd) && unset OLDPWD

# Load original environment
. /.runcvm/config

# Load original entrypoint
mapfile -t ARGS </.runcvm/entrypoint

# Clean RUNCVM env vars
clean_env

IFS=':' read -r uid gid additionalGids <<< "$RUNCVM_UIDGID"
exec $RUNCVM_GUEST/bin/s6-applyuidgid -u $uid -g $gid -G "$additionalGids" "${ARGS[@]}"