#!/opt/runcvm/bin/bash

. /opt/runcvm/scripts/runcvm-vm-defaults && PATH="$RUNCVM_PATH"

OPTS=(--retry-path --statedir /.runcvm)

if [ -f "/dev/virtio-ports/org.qemu.guest_agent.0" ]; then
  DEV="/dev/virtio-ports/org.qemu.guest_agent.0"
else
  DEV=$(ls /dev/vport* | head -n 1)
  
  if [ -n "$DEV" ] && [ -c "$DEV" ]; then  
    OPTS+=(-p "$DEV")
  fi
fi

if [ -z "$DEV" ]; then
  exit 0
fi

exec qemu-ga "${OPTS[@]}"
