#!/opt/runcvm/bin/sh

. /opt/runcvm/scripts/runcvm-ctr-defaults && PATH="$RUNCVM_PATH"

# runcvm-init execs this script when it exits.
# It:
# - performs any post-VM tests.
# - retrieves any saved exit code.
# - resets terminal readline horizontal scroll
# - exits with exit code

if [ -f /.runcvm/exitcode ]; then
  read CODE </.runcvm/exitcode

  # Convert negative codes to positive and ensure in acceptable range (0-255)
  CODE=$(( $CODE & 255 ))
elif [ -n "$1" ]; then
  CODE=$(( ($1+1)/2 ))
fi

# Workaround for https://github.com/cirosantilli/linux-kernel-module-cheat/issues/110
tput smam 2>/dev/null

exit ${CODE:-0}