#!/.runcvm/guest/bin/bash

# Load original environment
. /.runcvm/config

# Load defaults and aliases
. $RUNCVM_GUEST/scripts/runcvm-ctr-defaults

if [ -f /.runcvm/once ]; then
  poweroff
  exit 0
else
  touch /.runcvm/once
fi

# Change to saved PWD
cd $(cat /.runcvm/pwd) && unset OLDPWD

# Reload original environment
. /.runcvm/config

# Load original entrypoint
mapfile -t ARGS </.runcvm/entrypoint

# Clean RUNCVM env vars
clean_env

IFS=':' read -r uid gid additionalGids <<< "$RUNCVM_UIDGID"
exec $RUNCVM_GUEST/bin/s6-applyuidgid -u $uid -g $gid -G "$additionalGids" "${ARGS[@]}"